<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5f97b418-2862-4b00-b888-74541ee7a2e3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AuditLog.cs" />
    <Compile Remove="Blog.cs" />
    <Compile Remove="BlogCategory.cs" />
    <Compile Remove="ChildProfile.cs" />
    <Compile Remove="ContactRequest.cs" />
    <Compile Remove="Contract.cs" />
    <Compile Remove="ContractTemplate.cs" />
    <Compile Remove="Conversation.cs" />
    <Compile Remove="ConversationParticipant.cs" />
    <Compile Remove="DTO\**" />
    <Compile Remove="Faq.cs" />
    <Compile Remove="FavoriteJobPosting.cs" />
    <Compile Remove="FavoriteNanny.cs" />
    <Compile Remove="HiringRecord.cs" />
    <Compile Remove="Interview.cs" />
    <Compile Remove="JobApplication.cs" />
    <Compile Remove="JobPosting.cs" />
    <Compile Remove="JobRequirement.cs" />
    <Compile Remove="JobScheduleRequirement.cs" />
    <Compile Remove="Message.cs" />
    <Compile Remove="NannyAvailability.cs" />
    <Compile Remove="NannyCertificate.cs" />
    <Compile Remove="NannyMatchingDbContext.cs" />
    <Compile Remove="NannyProfile.cs" />
    <Compile Remove="NannySkill.cs" />
    <Compile Remove="Notification.cs" />
    <Compile Remove="OtpCode.cs" />
    <Compile Remove="ParentProfile.cs" />
    <Compile Remove="RefreshToken.cs" />
    <Compile Remove="Report.cs" />
    <Compile Remove="Review.cs" />
    <Compile Remove="Role.cs" />
    <Compile Remove="Skill.cs" />
    <Compile Remove="SubscriptionPlan.cs" />
    <Compile Remove="SystemSetting.cs" />
    <Compile Remove="Transaction.cs" />
    <Compile Remove="User.cs" />
    <Compile Remove="UserRole.cs" />
    <Compile Remove="UserSubscription.cs" />
    <Compile Remove="VerificationDocument.cs" />
    <Compile Remove="VerificationRequest.cs" />
    <Content Remove="DTO\**" />
    <EmbeddedResource Remove="DTO\**" />
    <None Remove="DTO\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="8.6.3" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="MailKit" Version="4.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.23">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Data\\vn-addresses.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
