// auto-generated by gen_service_interfaces.py — edit if needed
using System.Net.Mail;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using Nanny_BackEnd.DTOs.Account;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IAdminAccountService
{
    Task<AccountListResponse> AdminViewModeratorAccountListAsync(
        string? search,
        int? status,
        int page,
        int pageSize);
    Task<(bool Success, AccountDto? Data, string? Message)> AdminViewModeratorAccountDetailAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message, object? Data)> AdminCreateModeratorAccountAsync(
        CreateModeratorRequest request);
    Task<(bool Success, int StatusCode, string Message)> AdminUpdateModeratorAccountAsync(
        Guid id,
        UpdateAccountStatusRequest request);
    Task<(bool Success, int StatusCode, string Message)> AdminToggleModeratorAccountAsync(
        Guid id,
        UpdateAccountStatusRequest request);
}
