// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Google.Apis.Auth;
using Nanny_BackEnd.DTOs.Auth;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;
using Nanny_BackEnd.Validations;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IAuthService
{
    Task RegisterAsync(RegisterRequest request);
    Task<(LoginResponse? Response, bool IsPending)> LoginAsync(LoginRequest request);
    Task<LoginResponse> RefreshTokenAsync(RefreshTokenRequest request);
    Task<LoginResponse> GoogleLoginAsync(GoogleLoginRequest request);
    Task ChangePasswordAsync(Guid userId, ChangePasswordRequest request);
    Task<(bool success, string message)> ForgotPasswordAsync(string email);
    Task ResetPasswordAsync(ResetPasswordRequest request);
    Task VerifyEmailAsync(VerifyEmailRequest request);
    Task ResendVerifyEmailAsync(string email);
    Task LogoutAsync(string refreshToken);
    Task<LoginResponse> SetRoleAsync(Guid userId, string role);
}
