// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Nanny_BackEnd.DTOs.BlogCategory;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IBlogCategoryService
{
    Task<BlogCategoryListResponse> ModeratorViewBlogCategoryListAsync(
        string? search, int page, int pageSize, bool? isDeleted = null);
    Task<(bool Success, int StatusCode, string Message, BlogCategoryDto? Data)>
        ModeratorViewBlogCategoryDetailAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message, BlogCategoryDto? Data)>
        ModeratorCreateBlogCategoryAsync(CreateBlogCategoryRequest req, Guid? createdBy);
    Task<(bool Success, int StatusCode, string Message)>
        ModeratorUpdateBlogCategoryAsync(Guid id, UpdateBlogCategoryRequest req, Guid? updatedBy);
    Task<(bool Success, int StatusCode, string Message)>
        ModeratorToggleCategoryStatusAsync(Guid id, bool activate);
}
