// auto-generated by gen_service_interfaces.py — edit if needed
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;

namespace Nanny_BackEnd.Services.Interfaces;

public interface ICassoService
{
    bool isWebhookAuthorized(string? secureToken);
    Task syncTransactions();
}
