// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using MailKit.Net.Smtp;
using MimeKit;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IEmailService
{
    Task SendOtpEmailAsync(string toEmail, string otpCode, string purpose);
}
