// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IExportService
{
    Task<byte[]> ExportSystemDataToExcelAsync();
}
