// auto-generated by gen_service_interfaces.py — edit if needed
using System.Text.Json;
using System.Threading.Tasks;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IGeocodingService
{
    Task<(decimal Lat, decimal Lng)?> geocode(
        string? location, string? city, string? district);
}
