// auto-generated by gen_service_interfaces.py — edit if needed
using Nanny_BackEnd.DTOs.Hiring;
using System.Threading.Tasks;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;
using System.Text.RegularExpressions;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IHiringService
{
    Task<List<JobApplicantDto>> GetApplicantsAsync(Guid jobPostingId, Guid parentUserId);
    Task ApproveApplicantAsync(Guid jobPostingId, Guid jobAppId, Guid parentUserId);
    Task<NannyHireContextDto> GetNannyHireContextAsync(Guid jobPostingId, Guid jobAppId, Guid parentUserId);
    Task<HiringConfirmedDto> ConfirmHiringAsync(
        Guid jobPostingId, Guid jobAppId, Guid parentUserId, ConfirmHiringDto dto);
    Task<HiringConfirmedDto> ConfirmHiringByContactRequestAsync(
        Guid contactRequestId, Guid parentUserId, ConfirmHiringDto dto);
    Task<HiringOfferDetailDto> GetHiringOfferDetailAsync(Guid hiringRecordId, Guid currentUserId);
    Task RespondToOfferAsync(Guid hiringRecordId, Guid nannyUserId, RespondToOfferDto dto);
    Task CompleteHiringAsync(Guid hiringRecordId, Guid parentUserId);
    Task<List<object>> GetTemplatesForHiringAsync();
}
