// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Nanny_BackEnd.DTOs.JobPosting;
using Nanny_BackEnd.DTOs.Search;
using Nanny_BackEnd.DTOs.Subscription;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IJobService
{
    Task<List<SearchJobResponse>> findJobs(
        SearchJobRequest filters,
        double? nannyLat = null,
        double? nannyLng = null,
        Guid? currentUserId = null,
        bool canSeeNannyOnlyJobs = false,
        Guid? currentNannyProfileId = null);
    Task<List<SearchJobResponse>> getMyJobs(Guid parentProfileId);
    Task<(List<SearchJobResponse> Items, int TotalCount)> getFavoriteJobs(
        Guid nannyProfileId,
        int page = 1,
        int pageSize = 20,
        Guid? currentUserId = null);
    Task<List<SearchJobResponse>> searchByTitle(string? title);
    Task<JobPostingDetailResponse> getDetail(Guid jobId);
    Task<JobPostingPrefillResponse> getCreatePrefill(Guid parentProfileId);
    Task<Guid> createJob(Guid parentProfileId, CreateJobPostingRequest req);
    Task updateJob(Guid jobId, Guid parentProfileId, UpdateJobPostingRequest req);
    Task moderateJob(Guid jobId, Guid moderatorUserId, bool approved, string? note);
    Task deletePost(Guid jobId, Guid parentProfileId);
    Task addFavoriteJob(Guid nannyProfileId, Guid jobPostingId);
    Task<bool> toggleFavoriteJob(Guid nannyProfileId, Guid jobPostingId, Guid actorUserId);
    Task<(List<SearchJobResponse> Items, int TotalCount)> GetModeratorJobsAsync(
        int? status,
        int? moderationStatus,
        string? search,
        int page,
        int pageSize);
    Task ReviewJobAsync(Guid jobId, Guid moderatorUserId, int moderationStatus, string? note);
    Task DeactivateJobAsync(Guid jobId, Guid moderatorUserId);
    Task<(List<SearchJobResponse> Items, int TotalCount)> ModeratorViewJobListAsync(
        int? status,
        int? moderationStatus,
        string? search,
        int page,
        int pageSize);
    Task<JobPostingDetailResponse> ModeratorViewJobDetailAsync(Guid jobId);
    Task ModeratorReviewJobAsync(Guid jobId, Guid moderatorUserId, ModerateJobPostingRequest request);
    Task ModeratorDeactivateJobAsync(Guid jobId, Guid moderatorUserId);
    Task<BackfillJobCoordinatesResult> BackfillJobCoordinatesAsync(
        BackfillJobCoordinatesRequest request,
        Guid? actorUserId = null,
        CancellationToken cancellationToken = default);
}
