// auto-generated by gen_service_interfaces.py — edit if needed
using System.IdentityModel.Tokens.Jwt;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IJwtService
{
    (string Token, DateTime ExpiresAt, string JwtId) GenerateAccessToken(User user, List<string> roles);
    string GenerateRefreshToken();
    (Guid? UserId, string? JwtId) GetTokenClaims(string token);
}
