// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Nanny_BackEnd.DTOs.JobPosting;
using Nanny_BackEnd.DTOs.Search;
using Nanny_BackEnd.DTOs.Subscription;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IModeratorJobService
{
    Task<(List<SearchJobResponse> Items, int TotalCount)> ModeratorViewJobListAsync(
        int? status,
        int? moderationStatus,
        string? search,
        int page,
        int pageSize);
    Task<JobPostingDetailResponse> ModeratorViewJobDetailAsync(Guid jobId);
    Task ModeratorReviewJobAsync(Guid jobId, Guid moderatorUserId, ModerateJobPostingRequest request);
    Task ModeratorDeactivateJobAsync(Guid jobId, Guid moderatorUserId);
}
