// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Nanny_BackEnd.DTOs.Account;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IModeratorAccountService
{
    Task<AccountListResponse> ModeratorViewAccountListAsync(
        string? role,
        int? status,
        string? search,
        int page,
        int pageSize);
    Task<(bool Success, AccountDto? Data, string? Message)> ModeratorViewAccountDetailAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message, object? Data)> ModeratorToggleAccountStatusAsync(
        Guid id,
        UpdateAccountStatusRequest request);
}
