// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Nanny_BackEnd.DTOs.Verification;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IModeratorVerificationService
{
    Task<VerificationRequestListResponse> ModeratorViewVerificationListAsync(
        int? status,
        int? requestType,
        string? search,
        int page,
        int pageSize);
    Task<(bool Success, VerificationRequestDetailDto? Data, string? Message)> ModeratorViewVerificationDetailAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message)> ModeratorReviewVerificationAsync(
        Guid id,
        Guid moderatorId,
        ReviewVerificationRequest request);
}
