// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Nanny_BackEnd.DTOs.Nanny;
using Nanny_BackEnd.DTOs.Subscription;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface INannyService
{
    Task<NannyPagedResultResponse> GetListAsync(NannyListRequest request, Guid? currentParentProfileId = null);
    Task<NannyDetailResponse> GetDetailAsync(Guid nannyProfileId, Guid? currentParentProfileId = null);
    Task<NannyPagedResultResponse> GetFavoritesAsync(Guid parentProfileId, int page = 1, int pageSize = 12);
    Task<(bool IsFavorite, Guid NannyUserId)> ToggleFavoriteAsync(Guid parentProfileId, Guid nannyProfileId, Guid actorUserId);
}
