// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Nanny_BackEnd.DTOs.Profile;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;
using Nanny_BackEnd.Enums;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IOnboardingService
{
    Task<OnboardingStatusDto> GetStatusAsync(Guid userId);
    Task<List<SkillSelectionDto>> GetAllSkillsAsync();
    Task<NannyProfile> UpdateNannyProfileAsync(Guid userId, UpdateNannyProfileRequest request);
    Task UpdateNannySkillsAsync(Guid userId, UpdateNannySkillsRequest request);
    Task UpdateNannyAvailabilityAsync(Guid userId, UpdateNannyAvailabilityRequest request);
}
