// auto-generated by gen_service_interfaces.py — edit if needed
using System.Security.Cryptography;
using System.Threading.Tasks;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IOtpService
{
    Task<string> GenerateAsync(string email, OtpPurpose purpose, Guid? userId = null);
    Task<OtpCode?> ValidateAsync(string email, string code, OtpPurpose purpose);
}
