// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Nanny_BackEnd.DTOs.Profile;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IProfileService
{
    Task<string> UploadAvatarAsync(Guid userId, IFormFile file);
    Task<PersonalProfileDto> GetPersonalProfileAsync(Guid userId);
    Task<PersonalProfileDto> GetPublicProfileAsync(Guid? requesterUserId, Guid targetUserId);
    Task<PersonalProfileDto> UpdatePersonalInfoAsync(Guid userId, UpdatePersonalInfoRequest request);
    Task AddNannyCertificateAsync(Guid userId, CreateNannyCertificateRequest request);
    Task<List<ChildProfileDto>> GetChildProfilesAsync(Guid userId);
    Task<ChildProfileDto> CreateChildProfileAsync(Guid userId, CreateChildProfileRequest request);
    Task<ChildProfileDto> UpdateChildProfileAsync(Guid userId, Guid childId, UpdateChildProfileRequest request);
    Task DeleteChildProfileAsync(Guid userId, Guid childId);

    Task<ParentProfile?> GetParentProfileByUserIdAsync(Guid userId);
    Task<Guid?> GetParentProfileIdByUserIdAsync(Guid userId);
    Task UpdateParentOnboardingProfileAsync(Guid userId, UpdateParentProfileRequest request);
}
