// auto-generated by gen_service_interfaces.py — edit if needed
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Nanny_BackEnd.DTOs.Report;
using Nanny_BackEnd.Exceptions;
using Nanny_BackEnd.Helpers;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IReportService
{
    Task<Guid> ReportJobPostingAsync(Guid jobPostingId, Guid reporterUserId, CreateReportRequest request);
    Task<Guid> ReportProfileAsync(Guid profileUserId, Guid reporterUserId, CreateReportRequest request);
    Task<ReportListResponse> GetModeratorReportsAsync(
        int? status,
        string? entityType,
        string? search,
        int page,
        int pageSize);
    Task<(bool Success, ReportDetailDto? Data, string? Message)> GetModeratorReportDetailAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message)> ResolveReportAsync(
        Guid id,
        Guid moderatorUserId,
        ResolveReportRequest request);
    Task<(bool Success, int StatusCode, string Message)> ToggleReportStatusAsync(
        Guid id,
        Guid moderatorUserId,
        bool isActive);
}
