// auto-generated by gen_service_interfaces.py — edit if needed
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Nanny_BackEnd.DTOs.Review;
using Nanny_BackEnd.Enums;
using Nanny_BackEnd.Models;
using Nanny_BackEnd.Repositories.Interfaces;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IReviewService
{
    Task<ReviewDto> CreateReviewAsync(Guid parentUserId, CreateReviewRequest request);
    Task<ReviewListResponse> GetNannyReviewsAsync(Guid nannyUserId, int page = 1, int pageSize = 10);
    Task<List<ReviewableHiringRecordDto>> GetReviewableHiringRecordsAsync(Guid parentUserId);
    Task<List<MyReviewDto>> GetMyReviewsAsync(Guid reviewerUserId);
}
