// auto-generated by gen_service_interfaces.py — edit if needed
using Nanny_BackEnd.DTOs.Account;
using System.Threading.Tasks;
using Nanny_BackEnd.Repositories.Interfaces;
using System.Text.RegularExpressions;

namespace Nanny_BackEnd.Services.Interfaces;

public interface IUserService
{
    Task<AccountListResponse> GetAccountsAsync(
        string? role,
        int? status,
        string? search,
        int page,
        int pageSize);
    Task<(bool Success, AccountDto? Data, string? Message)> GetAccountAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message, object? Data)> UpdateStatusAsync(Guid id, UpdateAccountStatusRequest request);
    Task<AccountListResponse> GetModeratorsAsync(
        string? search, int? status, int page, int pageSize);
    Task<(bool Success, AccountDto? Data, string? Message)> GetModeratorAsync(Guid id);
    Task<(bool Success, int StatusCode, string Message, object? Data)> CreateModeratorAsync(
        CreateModeratorRequest request);
}
